### ISSUE TITLE
change edit/delete buttons 

### ISSUE THREAD

**Issue by array415** [natapoli90/project-01#2]

**Comment by natapoli90** [comment]
.glyphicon-plus, .glyphicon-ok {
  color: green;
  background-color: rgba(0,0,0,0);
}
.glyphicon-pencil {
  color: orange;
  background-color: rgba(0,0,0,0);
}
.glyphicon-trash {
  color: red;
  background-color: rgba(0,0,0,0);
}
 got it working and change the colors!
